/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'namho' at '9/16/16 11:03 AM' with Gradle 2.13
 *
 * @author namho, @date 9/16/16 11:03 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
